name: Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        flake8 src/ tests/ --max-line-length=120 --ignore=E501,W503

    - name: Run type checking
      run: |
        mypy src/ --ignore-missing-imports

    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=xml
      env:
        GHL_CLIENT_ID: test_client_id
        GHL_CLIENT_SECRET: test_client_secret

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
